### ISSUE TITLE
Commands with output not working

### ISSUE THREAD

**Issue by ylecuyer** [coolwanglu/neovim.as#4]
Open neovim.as and type `:ls`

Expected output:

```
:ls
  1 %a   "[No Name]"                    line 1
Press ENTER or type command to continue
```

Current output:

```
Press ENTER or type command to continue line 1
```

**Comment by neojski** [comment]
It worth mentioning that `ui.coffee` throws:

```
"Error: Failed to execute 'getImageData' on 'CanvasRenderingContext2D': The source height is 0.
    at Error (native)
    at UI.nv_scroll (/home/neo/neovim.as/src/nvim/ui.js:420:22)
    at UI.handle_redraw (/home/neo/neovim.as/src/nvim/ui.js:305:25)
    at Session.<anonymous> (/home/neo/neovim.as/src/nvim/nvim.js:33:29)
    at Session.emit (events.js:119:17)
    at Session._parse_message (/home/neo/neovim.as/node_modules/msgpack5rpc/index.js:101:10)
    at Decoder.<anonymous> (/home/neo/neovim.as/node_modules/msgpack5rpc/index.js:42:11)
    at Decoder.emit (events.js:116:17)
    at Decoder.<anonymous> (/home/neo/neovim.as/node_modules/msgpack5rpc/node_modules/msgpack5/node_modules/readable-stream/lib/_stream_readable.js:786:14)
    at Decoder.emit (events.js:113:17)", source: /home/neo/neovim.as/src/nvim/ui.js (315)
```

**Comment by coolwanglu** [comment]
Can you try to comment this line out: https://github.com/coolwanglu/neovim.as/blob/master/src/nvim/ui.coffee#L297

There was a bug (https://github.com/mcollina/msgpack5/issues/14) in msgpack5, making 1.5.0 and 1.6.0 not compatible with each other.  I'll comment this line out when this PR(https://github.com/tarruda/node-msgpack5rpc/pull/1) is merged.

**Comment by coolwanglu** [comment]
Oh, it's actually about setting default scroll region. Fixed in master branch.
